# Form implementation generated from reading ui file 'cart.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_cart(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(790, 846)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addDeleteLay = QtWidgets.QHBoxLayout()
        self.addDeleteLay.setObjectName("addDeleteLay")
        self.addProduct = QtWidgets.QPushButton(parent=Form)
        self.addProduct.setObjectName("addProduct")
        self.addDeleteLay.addWidget(self.addProduct)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.addDeleteLay.addItem(spacerItem)
        self.deleteProduct = QtWidgets.QPushButton(parent=Form)
        self.deleteProduct.setObjectName("deleteProduct")
        self.addDeleteLay.addWidget(self.deleteProduct)
        self.verticalLayout.addLayout(self.addDeleteLay)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.title_4 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_4.setFont(font)
        self.title_4.setObjectName("title_4")
        self.horizontalLayout_5.addWidget(self.title_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.isAdmin = QtWidgets.QCheckBox(parent=Form)
        self.isAdmin.setObjectName("isAdmin")
        self.horizontalLayout_5.addWidget(self.isAdmin)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.title_5 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_5.setFont(font)
        self.title_5.setObjectName("title_5")
        self.horizontalLayout_6.addWidget(self.title_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 770, 729))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.products_grid = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.products_grid.setObjectName("products_grid")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addProduct.setText(_translate("Form", "Add product"))
        self.deleteProduct.setText(_translate("Form", "Delete product"))
        self.title_4.setText(_translate("Form", "Profile"))
        self.isAdmin.setText(_translate("Form", "login as admin"))
        self.title_5.setText(_translate("Form", "Cart"))
