# Form implementation generated from reading ui file 'card.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Card(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.img = QtWidgets.QLabel(parent=Form)
        self.img.setMinimumSize(QtCore.QSize(0, 200))
        self.img.setText("")
        self.img.setObjectName("img")
        self.verticalLayout.addWidget(self.img)
        self.product_name = QtWidgets.QLabel(parent=Form)
        self.product_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.product_name.setObjectName("product_name")
        self.verticalLayout.addWidget(self.product_name)
        self.product_price = QtWidgets.QLabel(parent=Form)
        self.product_price.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.product_price.setObjectName("product_price")
        self.verticalLayout.addWidget(self.product_price)
        self.product_quanity = QtWidgets.QLabel(parent=Form)
        self.product_quanity.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.product_quanity.setObjectName("product_quanity")
        self.verticalLayout.addWidget(self.product_quanity)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.product_name.setText(_translate("Form", "НАЗВАНИЕ ПРОДУКТА"))
        self.product_price.setText(_translate("Form", "ЦЕНА"))
        self.product_quanity.setText(_translate("Form", "КОЛИЧЕСТВО"))
