# Form implementation generated from reading ui file 'deleteProduct.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_deleteProduct(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(413, 124)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.deleteName = QtWidgets.QLineEdit(parent=Form)
        self.deleteName.setObjectName("deleteName")
        self.horizontalLayout_6.addWidget(self.deleteName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.chngLable_2 = QtWidgets.QLabel(parent=Form)
        self.chngLable_2.setObjectName("chngLable_2")
        self.horizontalLayout_6.addWidget(self.chngLable_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.confrimBtn = QtWidgets.QPushButton(parent=Form)
        self.confrimBtn.setObjectName("confrimBtn")
        self.verticalLayout.addWidget(self.confrimBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.chngLable_2.setText(_translate("Form", "Name"))
        self.confrimBtn.setText(_translate("Form", "OK"))
