# Form implementation generated from reading ui file 'changeInfo.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_changeInfo(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(433, 430)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.changeQuanity = QtWidgets.QLineEdit(parent=Form)
        self.changeQuanity.setObjectName("changeQuanity")
        self.horizontalLayout.addWidget(self.changeQuanity)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.chngLabel_2 = QtWidgets.QLabel(parent=Form)
        self.chngLabel_2.setObjectName("chngLabel_2")
        self.horizontalLayout.addWidget(self.chngLabel_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.changePrice = QtWidgets.QLineEdit(parent=Form)
        self.changePrice.setObjectName("changePrice")
        self.horizontalLayout_4.addWidget(self.changePrice)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.changLabel = QtWidgets.QLabel(parent=Form)
        self.changLabel.setObjectName("changLabel")
        self.horizontalLayout_4.addWidget(self.changLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.changeDate = QtWidgets.QLineEdit(parent=Form)
        self.changeDate.setObjectName("changeDate")
        self.horizontalLayout_2.addWidget(self.changeDate)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.chngLabel = QtWidgets.QLabel(parent=Form)
        self.chngLabel.setObjectName("chngLabel")
        self.horizontalLayout_2.addWidget(self.chngLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cahngeDescription = QtWidgets.QLineEdit(parent=Form)
        self.cahngeDescription.setObjectName("cahngeDescription")
        self.horizontalLayout_3.addWidget(self.cahngeDescription)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.chngLable = QtWidgets.QLabel(parent=Form)
        self.chngLable.setObjectName("chngLable")
        self.horizontalLayout_3.addWidget(self.chngLable)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.confrimBtn = QtWidgets.QPushButton(parent=Form)
        self.confrimBtn.setObjectName("confrimBtn")
        self.verticalLayout.addWidget(self.confrimBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.chngLabel_2.setText(_translate("Form", "Quanity"))
        self.changLabel.setText(_translate("Form", "Price"))
        self.chngLabel.setText(_translate("Form", "Expiration date"))
        self.chngLable.setText(_translate("Form", "Description"))
        self.confrimBtn.setText(_translate("Form", "OK"))
